from pathlib import Path
import json, subprocess, sys, unittest
ROOT=Path(__file__).resolve().parent; OUT=ROOT/'artifacts/tcja_pass40_human_story.json'; SMOKE=ROOT/'artifacts/SMOKE_CAST_PASS_40.txt'
subprocess.run([sys.executable,'-m','src.human_story_engine','--court',str(ROOT/'artifacts/tcja_pass39_truth_court.json'),'--out',str(OUT)],cwd=ROOT,check=True)
suite=unittest.defaultTestLoader.discover(str(ROOT/'tests'),pattern='test_human_story_engine.py'); result=unittest.TextTestRunner(verbosity=1).run(suite)
if not result.wasSuccessful(): print('NEEDS REVIEW: Pass 40 focused checks failed.'); raise SystemExit(1)
p=json.loads(OUT.read_text(encoding='utf-8'))
lines=['========================================================================',' BILL X-RAY NEXT - PASS 40 SMOKE CAST',' HUMAN STORY ENGINE - FIRST MOMENT OF TRUTH','========================================================================','','YOUR DUTIES THIS PASS','  1. Run ONE_CLICK_PASS_40.bat from this project folder.','  2. Read the story printed below as a HUMAN, not as a developer.','  3. Read the machine verdict after the story.','  4. Send the full smoke cast back to the team.','','WHAT THIS PASS MUST PROVE','  - Court-cleared facts can become ordinary continuous prose.','  - Question-only findings remain visibly questions.','  - The writer does not fill evidence gaps with confident storytelling.','  - The machine can admit when it has NOT earned a satisfying essay yet.','',f"PASS 40: wrote {p['word_count']} words from {p['supported_fact_count']} court-cleared facts",'Dependency-free focused checks: 6/6 passed','','--------------------- I READ THE BILL ---------------------',p['story'],'-----------------------------------------------------------','',f"MACHINE VERDICT: {p['release_readiness']}",f"DIAGNOSIS: {p['diagnosis']}",'','CLEAR: PASS 40 completed as an honesty test. CLEAR does NOT mean the essay is finished.','It means the Human Story Engine obeyed the evidence gate and exposed the next bottleneck instead of bluffing.','Smoke cast saved to: artifacts\\SMOKE_CAST_PASS_40.txt']
text='\n'.join(lines); SMOKE.write_text(text,encoding='utf-8'); print(text)
