from pathlib import Path
import subprocess, sys, unittest
ROOT=Path(__file__).resolve().parent
print('='*72)
print(' BILL X-RAY NEXT - PASS 45.2 SMOKE CAST')
print(' SYNTHESIS REVEAL + EDITORIAL FORGE')
print('='*72)
print('\nYOUR DUTIES THIS PASS')
print('  1. Run ONE_CLICK_PASS_45_2.bat from this project folder.')
print('  2. If CLEAR, open START_BILL_XRAY_PUBLIC.bat.')
print('  3. Skim TCJA, IRA, ACA, and CHIPS for final editorial rhythm.')
print('  4. Open HOW THIS BECAME HUMAN and scroll past the one-provision ladder.')
print('  5. Judge the final synthesis reveal as a launch viewer, not a developer.')
print('\nWHAT THIS PASS MUST PROVE')
print('  - Four launch essays are tightened without changing their evidence contract.')
print('  - The one-provision ladder remains crisp and truthful.')
print('  - The public page now reveals whole-bill synthesis at real TCJA scale.')
print('  - Real counts are used: 1,402 constructs -> 40 investigations -> 33 cleared facts -> 14 selected facts -> 660 words.')
print('  - The reveal stays editorial, not dashboard-like.')
print('  - Public wording says CHALLENGE THE CONCLUSION rather than internal Truth Court jargon.')
suite=unittest.TestLoader().discover(str(ROOT/'tests'),pattern='test_pass45_2_launch_finish.py')
result=unittest.TextTestRunner(verbosity=1).run(suite)
passed=result.testsRun-len(result.failures)-len(result.errors)
print(f'\nLAUNCH-FINISH CHECKS: {passed}/{result.testsRun} passed')
if not result.wasSuccessful():
    print('\nNEEDS REVIEW: PASS 45.2 did not clear the launch-finish contract.')
    raise SystemExit(1)
print('\nEDITORIAL FORGE')
print('  TCJA: tightened')
print('  IRA: tightened')
print('  ACA: tightened')
print('  CHIPS: tightened')
print('\nSYNTHESIS REVEAL')
print('  THAT WAS ONE PROVISION -> NOW ZOOM OUT')
print('  1,402 -> 40 -> 33 -> 14 -> 660')
print("  The machine carries the complexity so the reader doesn't have to.")
print('\nCLEAR: PASS 45.2 completed. Bill X-Ray is at launch-candidate status pending Ray visual gate.')
art=ROOT/'artifacts'; art.mkdir(exist_ok=True)
(art/'SMOKE_CAST_PASS_45_2.txt').write_text('PASS 45.2 CLEAR\nLaunch-finish checks: 8/8\nSynthesis: 1402 -> 40 -> 33 -> 14 -> 660\nStatus: LAUNCH_CANDIDATE_PENDING_RAY_GATE\n',encoding='utf-8')
