from pathlib import Path
import json, subprocess, sys
ROOT=Path(__file__).resolve().parent
subprocess.check_call([sys.executable,'-m','unittest','tests.test_public_product','tests.test_public_language_clean_room'],cwd=ROOT)
raw=(ROOT/'public'/'data.js').read_text(encoding='utf-8').strip()
data=json.loads(raw[len('window.BXR_DATA = '):-1])
lines=[]; A=lines.append
A('='*72); A(' BILL X-RAY NEXT - PASS 44.1 SMOKE CAST'); A(' PUBLIC LANGUAGE CLEAN ROOM'); A('='*72); A('')
A('YOUR DUTIES THIS PASS')
A('  1. Run ONE_CLICK_PASS_44_1.bat from this project folder.')
A('  2. Read the CLEAR / NEEDS REVIEW result.')
A('  3. If CLEAR, open START_BILL_XRAY_PUBLIC.bat.')
A('  4. Click TCJA, IRA, and ACA and skim only the public articles.')
A('  5. Confirm the articles sound like journalism for citizens, not notes from our build process.')
A('  6. CHECK MY HOMEWORK should still open the unchanged evidence drawer.')
A('')
A('WHAT THIS PASS MUST PROVE')
A('  - The Pass 44 design and interaction remain intact.')
A('  - Development vocabulary is forbidden on the public article surface.')
A('  - TCJA, IRA, and ACA speak only about the law, the record, and uncertainty.')
A('  - Receipts and provenance remain available downstairs.')
A('')
A('PUBLIC LANGUAGE CONTRACT')
A('  Bill choices: 3 -> TCJA, IRA, ACA')
A('  Public evidence doorways: 1 -> CHECK MY HOMEWORK')
A(f"  TCJA public paragraphs: {len(data['tcja']['story'])}")
A(f"  IRA public paragraphs: {len(data['ira']['story'])}")
A(f"  ACA public paragraphs: {len(data['aca']['story'])}")
A('  Forbidden upstairs: cold trial, evidence packet, Reality Stack, pass/test/gate/engine/architecture language')
A('  Downstairs evidence terminology: allowed when the reader asks for receipts')
A('')
A('AUTOMATED VERDICT: CLEAR')
A('')
A('RAY CLEAN-ROOM GATE')
A('  Does every article now read as though the product simply knows the subject,')
A('  without telling the reader how we built or tested the product?')
text='\n'.join(lines)+'\n'
(ROOT/'artifacts'/'SMOKE_CAST_PASS_44_1.txt').write_text(text,encoding='utf-8')
print(text)
