from pathlib import Path
import json, subprocess, sys
ROOT=Path(__file__).resolve().parent
subprocess.check_call([sys.executable,'-m','unittest','tests.test_public_product'],cwd=ROOT)
raw=(ROOT/'public'/'data.js').read_text(encoding='utf-8').strip()
data=json.loads(raw[len('window.BXR_DATA = '):-1])
lines=[]; A=lines.append
A('='*72); A(' BILL X-RAY NEXT - PASS 44 SMOKE CAST'); A(' PUBLIC PRODUCT INVERSION'); A('='*72); A('')
A('YOUR DUTIES THIS PASS')
A('  1. Run ONE_CLICK_PASS_44.bat from this project folder.')
A('  2. Read the CLEAR / NEEDS REVIEW result.')
A('  3. If CLEAR, double-click START_BILL_XRAY_PUBLIC.bat.')
A('  4. Look at the FIRST SCREEN before clicking anything.')
A('  5. Ask: does this feel like an article, not a dashboard?')
A('  6. Then click CHECK MY HOMEWORK once and confirm the receipts appear.')
A('')
A('WHAT THIS PASS MUST PROVE')
A('  - Human meaning is the default surface.')
A('  - The 30-second version and column come before evidence machinery.')
A('  - There is exactly one public evidence doorway: CHECK MY HOMEWORK.')
A('  - Receipts remain hidden until requested.')
A('  - Backstage agent/process language does not leak onto the first screen.')
A('')
A('PUBLIC SURFACE CONTRACT')
A(f"  Bill choices: {len(data)} -> TCJA, IRA, ACA")
A('  Default first story: TCJA - The Tax Cut With More Than One Clock')
A('  Initial visible evidence panels: 0')
A('  Public evidence doorways: 1')
A(f"  TCJA receipts behind drawer: {len(data['tcja']['receipts'])}")
A(f"  IRA receipts behind drawer: {len(data['ira']['receipts'])}")
A(f"  ACA Reality Stack receipts behind drawer: {len(data['aca']['receipts'])}")
A('  Dependency requirement: none beyond a normal web browser')
A('')
A('AUTOMATED VERDICT: CLEAR')
A('')
A('RAY PUBLIC-SCREEN GATE')
A('  Open START_BILL_XRAY_PUBLIC.bat.')
A('  Before touching anything, take one screenshot of the first screen.')
A('  The pass fails if it feels like a dashboard, evidence console, or AI process demo.')
A('  The intended reaction is: "This looks like something I might actually read."')
text='\n'.join(lines)+'\n'
(ROOT/'artifacts'/'SMOKE_CAST_PASS_44.txt').write_text(text,encoding='utf-8')
print(text)
